/* Copyright (c) 2020 Ezzat Chamudi
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

const https = require('https');
const fs = require('fs');
const { execSync } = require('child_process');

fs.mkdirSync('./temp/', { recursive: true });

// Add notice
const notice = 'This folder is generated by script. Please don\'t edit the content manually.';
fs.writeFileSync('./temp/_notice.txt', notice, (err) => {
    if (err) {
        console.log(err);
    }
});

// Download files
(async () => {
    console.log('Downloading required files');

    await Promise.all([
        (() => new Promise((resolve) => {
            // Download Kanjium Antonyms
            https.get('https://raw.githubusercontent.com/echamudi/kanjium/master/data/source_files/antonyms.txt', (response) => {
                response.pipe(fs.createWriteStream('./temp/kanjium-antonyms.txt'));
                resolve();
            });
        }))(),
        (() => new Promise((resolve) => {
            // Download Kanjium Synonyms
            https.get('https://raw.githubusercontent.com/echamudi/kanjium/master/data/source_files/synonyms.txt', (response) => {
                response.pipe(fs.createWriteStream('./temp/kanjium-synonyms.txt'));
                resolve();
            });
        }))(),
        (() => new Promise((resolve) => {
            // Download Kanjium Lookalikes
            https.get('https://raw.githubusercontent.com/echamudi/kanjium/master/data/source_files/lookalikes.txt', (response) => {
                response.pipe(fs.createWriteStream('./temp/kanjium-lookalikes.txt'));
                resolve();
            });
        }))(),
        (() => new Promise((resolve) => {
            // Download Kanjium Variants
            https.get('https://raw.githubusercontent.com/echamudi/kanjium/master/data/source_files/variants.txt', (response) => {
                response.pipe(fs.createWriteStream('./temp/kanjium-variants.txt'));
                resolve();
            });
        }))(),
        (() => new Promise((resolve) => {
            // Download KANJIDIC
            https.get('https://raw.githubusercontent.com/echamudi/jp-resources-mirror/master/kanjidic2.xml.gz', (response) => {
                response.pipe(fs.createWriteStream('./temp/kanjidic2.xml.gz'));
                resolve();
            });
        }))(),
    ]);

    console.log('Downloading git files');

    // Download Kanji VG
    execSync('cd ./temp && git clone --depth 1 -b master https://github.com/echamudi/kanjivg.git && cd ..',
        {
            stdio: 'inherit',
        });

    console.log('Completed');
})();
