language: node_js

node_js:
  - "10"
  - "8"

os: 
  - linux

install:
  - npm install --only=prod
  - npm run download-source
  - npm run extract-kanjivg-tree
  - npm run extract-kanjium-data
  - npm link --only=prod
  - npm install -g mocha

script:
  - npm test
