language: node_js

node_js:
  - "10"
  - "12"

os: 
  - linux
  - windows
  - osx

install:
  - npm install
  - npx lerna bootstrap
  - npx lerna run --concurrency 1 --stream build

script:
  - npx lerna run --concurrency 1 --stream test
