language: node_js

node_js:
  - "10"
  - "12"

os: 
  - linux
  - windows

install:
  # Prepare libraries
  - npm install
  - npm run download-source
  - npm run extract-data
  - npm run compile
  - npm install rimraf -g
  - rimraf node_modules

  # Production only
  - npm install --only=prod
  - npm link --only=prod
  - npm install -g mocha

script:
  - npm test
