language: node_js

node_js:
  - "10"
  - "12"

os: 
  - linux

script:
  # Prepare libraries
  - npm install
  - npm run download-source
  - npm run extract-kanjivg-tree
  - npm run extract-kanjium-data
  - npm install rimraf -g
  - rimraf node_modules

  # Production only
  - npm install --only=prod
  - npm link --only=prod
  - npm install -g mocha

  # Run test
  - npm test
