name: Japanese Toolkit JS

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node-version: [10.x]
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Lerna Bootstrap
      run: |
        npm install
        npx lerna bootstrap

    - name: Build All
      run: |
        npx lerna run --concurrency 1 --stream build
    
    - name: Test Packages
      run: |
        npx lerna run --concurrency 1 --stream test
